
import "./globals.css";
import Navbar from "@/Components/navbar";
import {Poppins} from "next/font/google"



const poppins = Poppins({
  weight: ['400', '600'],
  subsets: ['latin'],
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    
  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-gradient-to-b from-black to-gray-900 text-white min-h-screen`}
      >
        <Navbar/>
        {/* <HeroSection/> */}
        {/* <Skills/> */}
        {children}
      </body>
    </html>
  );
}
